//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.10 at 08:04:54 PM EET 
//


package fi.tut.wsdl.someservice;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fi.tut.wsdl.someservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OutputElementOne_QNAME = new QName("http://www.tut.fi/wsdl/SomeService", "OutputElementOne");
    private final static QName _OperationTwoResponse_QNAME = new QName("http://www.tut.fi/wsdl/SomeService", "OperationTwoResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fi.tut.wsdl.someservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InputElementOne }
     * 
     */
    public InputElementOne createInputElementOne() {
        return new InputElementOne();
    }

    /**
     * Create an instance of {@link SomethingHappened }
     * 
     */
    public SomethingHappened createSomethingHappened() {
        return new SomethingHappened();
    }

    /**
     * Create an instance of {@link OperationTwo }
     * 
     */
    public OperationTwo createOperationTwo() {
        return new OperationTwo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tut.fi/wsdl/SomeService", name = "OutputElementOne")
    public JAXBElement<String> createOutputElementOne(String value) {
        return new JAXBElement<String>(_OutputElementOne_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tut.fi/wsdl/SomeService", name = "OperationTwoResponse")
    public JAXBElement<String> createOperationTwoResponse(String value) {
        return new JAXBElement<String>(_OperationTwoResponse_QNAME, String.class, null, value);
    }

}
