//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.10 at 08:04:54 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tut.fi/wsdl/SomeService", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fi.tut.wsdl.someservice;
